
# Use the Java image, for SSM tests
image: openjdk:alpine

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Install packages in a virtualenv, and cache them
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  # Try to install Python on the java image
  - apt-get update
  - apt-get install -y --no-install-recommends python3.9
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

format:
  script:
    - pip install black
    - python -m black --version # For debugging
    - python -m black . --check --verbose --diff --color --target-version py310

test:
  script:
    - pip install -r requirements-dev.txt
    - python -m pytest --version # For debugging
    - python -m pytest
  rules:
      # Only run test when commit is made to main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

bandit:
  script:
    - pip install bandit
    - python -m bandit --version # For debugging
    - python -m bandit $CI_PROJECT_DIR -r --exclude $CI_PROJECT_DIR/venv/,$CI_PROJECT_DIR/tests/,$CI_PROJECT_DIR/demo.py
  rules:
      # Only run bandit when commit is made to main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
