from enum import Enum, auto

class Type(Enum):
    LRB = auto()
    RRB = auto()
    LCB = auto()
    RCB = auto()
    LSB = auto()
    RSB = auto()
    # COMMENT = auto()
    # COMMENT_OPEN = auto()
    # COMMENT_CLOSE = auto()
    SEMICOLON = auto()
    DOUBLE_COLON = auto()
    ARROW = auto()
    COMMA = auto()
    PLUS = auto()
    MINUS = auto()
    STAR = auto()
    SLASH = auto()
    PERCENT = auto()
    DEQUALS = auto()
    LT = auto()
    GT = auto()
    LEQ = auto()
    GEQ = auto()
    NEQ = auto()
    EQ = auto()
    AND = auto()
    OR = auto()
    COLON = auto()
    NOT = auto()
    QUOTE = auto()
    HD = auto()
    TL = auto()
    FST = auto()
    SND = auto()
    IF = auto()
    WHILE = auto()
    RETURN = auto()
    VOID = auto()
    INT = auto()
    BOOL = auto()
    CHAR = auto()
    FALSE = auto()
    TRUE = auto()
    VAR = auto()
    ID = auto()
    DIGIT = auto()
    SPACE = auto()
    QUOTE_ERROR = auto()
    ERROR = auto()

    def to_type(type_str: str):
        return Type[type_str]

